[package]
name = "tame"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
crb.workspace = true
derive_more.workspace = true
log.workspace = true

[features]
default = ["std"]
std = [
    "crb/std",
]
