[package]
name = "cmq"
description = "Composable Message Queue"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
crb.workspace = true
derive_more.workspace = true
log.workspace = true
serde.workspace = true

[features]
default = ["std"]
std = [
    "crb/std",
]
