[package]
name = "tame_web"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
console_error_panic_hook.workspace = true
crb.workspace = true
log.workspace = true
wasm-logger.workspace = true

[features]
default = ["std"]
std = [
    "crb/std",
]
web = [
    "crb/std",
]
